# Generated by Django 2.0.4 on 2018-04-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='制造商')),
                ('country', models.CharField(max_length=10, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('url', models.URLField(default='https://sale.vmall.com/p20.html')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Maker')),
            ],
        ),
        migrations.CreateModel(
            name='PPhote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='产品照片', max_length=20)),
                ('url', models.URLField(default='https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1524129042512&di=176d16313df19f220cffff91e3bcacb2&imgtype=0&src=http%3A%2F%2Fimg1.mydrivers.com%2Fimg%2F20180327%2F9d40cf99ba02469fbecd444b67c1761a.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='PProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='华为p20', max_length=20)),
                ('description', models.TextField(default='暂无')),
                ('year', models.PositiveIntegerField(default=2018)),
                ('price', models.PositiveIntegerField(default=0)),
                ('pmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.PModel')),
            ],
        ),
        migrations.AddField(
            model_name='pphote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.PProduct'),
        ),
    ]
